# Generated by Django 2.2.6 on 2019-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20191029_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=25)),
                ('conference', models.CharField(max_length=25)),
                ('rank', models.ImageField(upload_to='')),
            ],
        ),
    ]
