# Generated by Django 2.2.6 on 2019-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20191101_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='schoolname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
