# Generated by Django 2.2.7 on 2019-12-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20191113_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefernces',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('race', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('schoolname', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('viewerId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('suggested', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
