# Generated by Django 2.2.7 on 2019-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20191203_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('suggested', models.CharField(max_length=10)),
            ],
        ),
    ]
