# Generated by Django 2.2.7 on 2019-12-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
