# Generated by Django 2.2.7 on 2019-12-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uid',
            field=models.CharField(default=-1, max_length=25),
            preserve_default=False,
        ),
    ]
