# Generated by Django 2.2.7 on 2019-12-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_company_perference_person_school_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='uid',
            field=models.CharField(max_length=10),
        )

    ]
