# Generated by Django 2.2.7 on 2019-12-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_auto_20191205_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
