# Generated by Django 2.2.7 on 2019-12-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_auto_20191205_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
