# Generated by Django 2.2.7 on 2019-12-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_auto_20191205_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
