# Generated by Django 2.2.7 on 2019-12-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_auto_20191205_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggest',
            new_name='Suggestions',
        ),
    ]
