# Generated by Django 2.2.7 on 2019-12-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0026_auto_20191205_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('suggested', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Suggest',
        ),
    ]
