# Generated by Django 2.2.7 on 2019-12-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0027_auto_20191205_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
