# Generated by Django 2.2.7 on 2019-12-05 03:03

from django.db import migrations, models
from django.db import connection


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0028_delete_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('suggested', models.CharField(max_length=10)),
            ],
        ),
    ]


