# Generated by Django 2.2.7 on 2019-12-05 07:23

from django.db import migrations, models
from django.db import connection


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0029_suggestions'),
    ]

    operations = [

        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(max_length=10)),
                ('otherid', models.IntegerField(max_length=10)),
                ('score', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='perference',
            name='uid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='uid',
            field=models.IntegerField(max_length=10),
        )
    ]

